SELECT CONCAT(commentid, CONCAT(' - ', userid)) AS id, BCOMMENTLIKE.RATETIME AS created, BCOMMENTLIKE.COMMENTID, USER.extid
FROM BLOGS.ROLLER_COMMENT_RATING AS bcommentlike
JOIN BLOGS.ROLLERUSER USER ON USER.id = BCOMMENTLIKE.USERID 