SELECT CONCAT(entryid, CONCAT (' - ', userid)) AS Id, WEBRATING.RATETIME AS created, WEBRATING.ENTRYID, USER.extid
FROM BLOGS.ROLLER_WEBLOGENTRY_RATING AS webrating
JOIN BLOGS.ROLLERUSER USER ON USER.id = WEBRATING.USERID 