SELECT DISTINCT tag.ID AS id, tag.create_date AS created,  tag.tag AS LABEL, USER.id AS userid, MREVSION.ID AS media_id
FROM WIKIS.TAG AS tag
JOIN WIKIS.MEDIA_TO_TAG AS mediatag ON tag.ID = MEDIATAG.TAG_ID 
JOIN WIKIS.MEDIA_REVISION mrevsion ON MREVSION.MEDIA_ID = MEDIATAG.MEDIA_ID 
JOIN WIKIS.MEDIA AS media ON media.ID = MEDIATAG.MEDIA_ID 
JOIN WIKIS.USER AS USER ON USER.ID = MEDIA.OWNER_USER_ID