SELECT BOARDPOST.NODEUUID AS id, BOARDPOST.TOPICID, BOARDPOST.DESCRIPTION AS content, BOARDPOST.CREATED AS created, BOARDPOST.NAME AS title, BOARDPOST.LASTMOD AS last_updated, 
BOARDPOST.FORUMUUID AS forumuuid, MEMBERPROFILE.EXID  
FROM FORUM.DF_NODE AS BoardPost 
JOIN FORUM.DF_MEMBERPROFILE AS Memberprofile ON BOARDPOST.CREATEDBY = MEMBERPROFILE.MEMBERID 
WHERE BOARDPOST.NODETYPE = 'forum/topic'
